inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "app/assets"
    - "app/channels"
    - "app/jobs"
    - "bin/*"
    - "lib/*"
    - "log/*"
    - "public/*"
    - "storage/*"
    - "tmp/*"
    - "vendor/*"
    - "**/Gemfile"
    - .git/**/*"
    - "spec/**/*"
    - "vendor/**/*"
  NewCops: enable
